# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/dma/friends/models/category/fields.yaml

# Model Class name
modelClass: DMA\Friends\Models\Category

# Default redirect location
defaultRedirect: dma/friends/categories

# Create page
create:
    title: Create Categories
    redirect: dma/friends/categories/update/:id
    redirectClose: dma/friends/categories

# Update page
update:
    title: Edit Categories
    redirect: dma/friends/categories
    redirectClose: dma/friends/categories

# Preview page
preview:
    title: Preview Categories