# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: @/plugins/dma/friends/models/usergroup/columns.yaml
filter: @/plugins/dma/friends/models/usergroup/config_filter.yaml

# Model Class name
modelClass: DMA\Friends\Models\UserGroup

# List Title
title: Manage Groups

# Link URL for each record
recordUrl: dma/friends/groups/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
