# ===================================
#  Relation Behavior Config
# ===================================

users:
    label: Users
    list: @/plugins/rainlab/user/models/user/columns.yaml
    form: @/plugins/rainlab/user/models/user/fields.yaml        
    pivot:
        title: Hello
        fields:
            membership_status:
                label: Membership status
                type: dropdown