# :::::::::::::::::::::::::::::::::::
#  Relation Behavior Config
# :::::::::::::::::::::::::::::::::::

users:
    label: Users
    list: @/plugins/dma/friends/controllers/groups/user_columns.yaml
    #form: @/plugins/dma/friends/controllers/groups/user_fields.yaml        
    manage:
        recordsPerPage: 10
        showSearch: true    
        
    # pivot:
    #     fields:
    #         membership_status:
    #             label: Membership status
    #             type: dropdown
    #             options:
    #                 PENDING   : PENDING
    #                 ACCEPTED  : ACCEPTED
    #                 REJECTED  : REJECTED
    #                 CANCELLED : CANCELLED
                
        
