# ===================================
#  Relation Behavior Config
# ===================================

users:
    label: Group members
    list: @/plugins/rainlab/user/models/user/columns.yaml
    form: @/plugins/rainlab/user/models/user/fields.yaml
    manage:
        recordsPerPage: 10